articulo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.lista_articulos, name='lista_articulos')
]

mi_aplicacion/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('saludo/', views.saludos),
    path('saludo-post/', views.saludo_post),
    path('saludo-vista-clase', views.SaludoView.as_view()),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('api/saludo-rest/', views.SaludoViewAPI.as_view(), name="saludo")
]

primerproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import inicio
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", inicio, name="inicio"),

    # URLS de cada APP
    path('mi-aplicacion/', include('mi_aplicacion.urls')),
    path('articulo/', include('articulo.urls')),
    path('producto/', include('producto.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

producto/urls.py
from django.urls import path
from . import views
from .views import ProductoListCreate, ProductoListCreate2

urlpatterns = [
    path('crear-producto/', views.crear_producto, name="crear_producto"),
    path('lista-productos/', views.lista_productos, name="producto_lista"),
    path('<int:pk>/', views.ProductoDetalleView.as_view(), name='producto_detalle'),
    path('api/productos/', ProductoListCreate.as_view(), name='producto-list-create'),
    path('api/productos2/', ProductoListCreate2.as_view(), name='producto-list-create2'),
    path('api/productos2/<int:pk>', ProductoListCreate2.as_view(), name='producto-list-create2'),
]

articulo/models.py
import random

from django.db import models

class Articulo(models.Model):
    titulo = models.CharField(max_length=100)
    contenido = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    version = models.IntegerField(default=1)

    def __str__(self):
        aleatorio = random.randint(1, 6)
        return f"{self.titulo}{aleatorio}"


class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    fecha_registro = models.DateTimeField(auto_now_add=True)

mi_aplicacion/models.py
from django.db import models

# Create your models here.

producto/models.py
from django.db import models

from articulo.models import Cliente
class Producto(models.Model):
    nombre = models.CharField(max_length=30)
    descripcion = models.TextField()
    precio = models.DecimalField(decimal_places=2, max_digits=10)

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    nombre_pedido = models.CharField(max_length=30)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True, blank=True)

user_custom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from .managers import CustomUserManager
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    bio = models.CharField(max_length=30)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

producto/forms.py
from django import forms
from .models import Producto


"""
class ProductoForm(forms.Form):
    nombre = forms.CharField(label='Nombre A', max_length=100)
    precio = forms.DecimalField(label='Precio', max_digits=10, decimal_places=2)
"""

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        #fields = ["nombre", "descripcion", "precio"]
        fields = "__all__"

user_custom/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("email",)

articulo/views.py
from django.shortcuts import render

from .models import Articulo


def lista_articulos(request):
    articulos = Articulo.objects.all()  #Consulta a la base de datos trayendo todos los objetos
    return render(request, 'lista_articulos.html', {'articulos': articulos})

mi_aplicacion/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response


def saludos(a):
    print(a) #imprime un objeto
    return HttpResponse("¡Hola, Django! Get")


def saludo_post(a):
    print(a) #imprime un objeto
    return HttpResponse("¡Hola, Django! Post")

class SaludoView(View):
    def get(self, request):
        return HttpResponse("¡Hola desde una vista basada en clase!")

    def post(self, request):
        ...


class SaludoViewAPI(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        return Response({"msg": "Saludo tipo rest autenticado"})

primerproyecto/views.py
from django.shortcuts import render


def inicio(request):
    return render (request, 'inicio.html')

producto/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .models import Producto
from .forms import ProductoForm
from django.contrib.auth.decorators import permission_required
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Producto
from .serializers import ProductoSerializer
from .permissions import group_required


@group_required('admin')
def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'lista_productos.html', {'productoss': productos})



class ProductoDetalleView(DetailView):
    model = Producto
    template_name = 'producto_detalle.html'



#@login_required
@permission_required('producto.add_producto', '/login/')
def crear_producto(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            #return redirect("producto_lista")
            return JsonResponse({"success": True, "message": "Producto creado con exito"})

        else:
            return JsonResponse({"success": False, "errors": form.errors}, status=400)
    else:
        form = ProductoForm()
    return render(request, 'crear_producto.html', {'form': form})




class ProductoListCreate(generics.ListCreateAPIView):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer


class ProductoListCreate2(APIView):

    def get(self, request):
        # AGREGAR AL PRIMER ELEMENTO DE LA RESPUESTA LA CLAVE "test: 1"
        #productos = Producto.objects.filter(descripcion="a")
        productos = list(Producto.objects.all())
        productos[0].test = 1
        serializer = ProductoSerializer(productos, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = ProductoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


    def put(self, request, pk=None):
        try:
            producto = Producto.objects.get(pk=pk)
        except Producto.DoesNotExist:
            return Response({"error": "Producto no encontrado"}, status=status.HTTP_404_NOT_FOUND)


        # Actualizar el producto
        serializer = ProductoSerializer(producto, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

user_custom/views.py
from django.shortcuts import render

# Create your views here.

articulo/templates/lista_articulos.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Artículos</title>
</head>
<body>
    <h1>Artículos</h1>
    <ul>
    {% for articulo in articulos %}
        <li>{{ articulo.titulo }} - {{ articulo.fecha_publicacion }}</li>
    {% endfor %}
    </ul>
</body>
</html>

producto/templates/crear_producto.html
{% extends 'inicio.html' %}

{% block title %}
    Crear producto
{% endblock %}

{% block content %}
    <h1>Crear producto</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>

    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        $('#enviar-producto').click(function(e){
            e.preventDefault();

            $.ajax({
                url: '/producto/crear-producto/',
                method: 'POST',
                data :{
                    nombre: $('#id_nombre').val(),
                    precio: $('#id_precio').val(),
                    descripcion: $('#id_descripcion').val(),
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                },
                success: function (response){
                    alert("Producto creado con exito!");
                },
                error: function (response){
                    alert("Producto no creado con exito!");
                }

            });

        });

    </script>

{% endblock %}

producto/templates/lista_productos.html
{% extends 'inicio.html' %}


{% block title %}
    Lista de productos
{% endblock %}

{% block content %}
    <h1>Productos</h1>
    <ul>
    {% for producto in productoss %}
        <li>
            <a href="{% url 'producto_detalle' producto.pk%}">
                Nombre {{producto.nombre}} - Descripcion: {{producto.descripcion}} el precio {{producto.precio}}
            </a>
        </li>
    {% endfor %}
    </ul>
    <a href="{% url 'crear_producto' %}" class="btn btn-primary">Agregar producto</a>
{% endblock %}

producto/templates/producto_detalle.html
{% extends 'inicio.html' %}

{% block title %}
    Detalles del producto
{% endblock %}

{% block content %}
    <h1>Producto</h1>
    <p><strong>Nombre</strong>  {{producto.nombre}}  </p>
    <p><strong>Descripcion</strong>  {{producto.descripcion}}  </p>
    <p><strong>Precio</strong>  {{producto.precio}}  </p>

    <a href="{% url 'producto_lista' %}">Volver a la lista de productos</a>
{% endblock %}

templates/inicio.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Mi Sitio</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'producto_lista' %}">Productos</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>